apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kalu1f5vn-go-gitops
  description: This is GitOps manifest for kalu1f5vn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kalu1f5vn-go
    janus-idp.io/tekton: kalu1f5vn-go
    backstage.io/kubernetes-id: kalu1f5vn-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kalu1f5vn-go
