apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kalu1f5vn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kalu1f5vn-go 
  name: kalu1f5vn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kalu1f5vn-go 
